title: CV | Kristof Meixner
description:  Researcher and Software Engineer with strong problem solving skills, a wide range of knowledge in software development and project management and several years of work experience.
url: https://kristofmeixner.github.io/
baseurl: 'https://kristofmeixner.github.io/'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
